project:
  type: book
  output-dir: docs

book:
  title: "The Human Exception"
  subtitle: "Why AI Will Enhance, Not Replace"
  author: "Sami Karam and Richard Sprague"
  date: "4/12/2025"
  search: true
  page-footer: "Copyright 2025 People+Capital, LLC"
  site-url: https://richardsprague.github.io/people-capital/
  downloads: [pdf, epub, docx]
  cover-image: _resources/book/HumanElementCover.jpg
  
  chapters:
    - index.qmd
    - intro.qmd
    - Ch01.qmd
    - Ch02.qmd
    - Ch03.qmd
    - Ch04.qmd
    - Ch05.qmd
    - Ch06.qmd
    - Ch07.qmd
    - Ch08.qmd
    - Ch09.qmd
    - Ch10.qmd
    - summary.qmd
    - about.qmd
    - references.qmd

bibliography: _resources/AI.bib
nocite: '@*'

format:
  html:
    theme: cosmo
    css: _resources/css/normalize.css
    standalone: true
    toc: true
    link-external-newwindow: true
    execute:
      fig-format: svg
  pdf:
    papersize: "Letter"
    mainfont: "Hoefler Text"
    toc: true
    documentclass: scrbook
    geometry: paperwidth=6in,paperheight=9in
    keep-tex: true
    header-includes:
      - \raggedbottom
    include-in-header:
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body:
      text: |
        \printindex
    standalone: true
    execute:
      fig-format: pdf
  docx:
    reference-doc: _resources/book/reference.docx

  epub:
    cover-image: _resources/book/HumanElementCover.jpg

