---
title: "About the Authors"
---


Sami J. Karam has worked in the financial markets for over three decades. He was formerly a fund manager at his own firm Seven Global LP and at Evergreen (now Wells Fargo), Kingdon and Soros in Boston and New York. He lives in New York City.

In 2012, Sami started populyst (population + analyst) as a site to research markets and demographics. His articles and interviews have appeared in Foreign Affairs, Quillette, National Review, New Geography, L’Express and other outlets.

He sometimes writes for expert sites for their institutional clients.

***

Richard Sprague has worked in technology for decades. He co-authors with Sami the weekly InvestAI etc. post. He and Sami were Wharton MBA classmates. 

Richard has been a senior executive at numerous technology firms, including Apple where, as an early employee in Japan, he was responsible for the launch of several Mac software products, and Microsoft where he led the Beijing-based development of Mac Excel. He currently works with startups to build what he calls "personal science": applying the latest technology to personalized health and wellness.
